Updated doc comments and description
blesta/gateway-cornerstone pull request #1
Opened 2020-04-30 16:05 UTC by abdyfranco

2020-04-30 16:08 UTC, abdyfranco commented
I didn't find the currencies supported by this gateway anywhere in the documentation, I can make a script that tries to automatically perform a transaction on each currency, to find out which currencies it supports.

2020-05-01 16:45 UTC, JReissmueller requested changes

2020-05-01 16:45 UTC, JReissmueller commented on apis/cornerstone_api_response.php
>          if ($this->response && isset($this->response->response)) {
This condition is redundant

2020-05-01 16:45 UTC, JReissmueller commented on cornerstone.php
> +        $this->Input->setErrors($this->getCommonError('unsupported'));
Should do the same for captureCc

2020-05-01 22:10 UTC, JReissmueller approved these changes

2020-05-01 22:15 UTC, merged